### ISSUE TITLE
[REQUEST] Switch from integrated -> nvidia instead of integrated -> hybrid -> nvidia

### ISSUE THREAD

**Issue by dreamsyntax** [bayasdev/envycontrol#149] opened 2023-12-19 02:20 UTC
**Is your feature request related to a problem? Please describe.**
* Linux Mint's GPU switcher allows for switching from integrated to nvidia with a logout
* Pop!OS GPU switcher allows for switching from integrated to nvidia with a reboot

With envycontrol, it is only possible to switch to nvidia while in hybrid.
Attempting to switch from integrated results in:
```
$ sudo envycontrol -s nvidia
Switching to nvidia mode
Enable ForceCompositionPipeline: False
Enable Coolbits: False
Successfully enabled nvidia-persistenced.service
ERROR: Could not find Nvidia GPU
Try switching to hybrid mode first!
``` 

**Describe the solution you'd like**
Being able to switch from integrated -> nvidia and back without switching to hybrid, rebooting, then switching to nvidia.

**Describe alternatives you've considered**
It's not a deal breaker so I can live with it if there is a technical blocker preventing this feature.

**Comment by bayasdev** [comment] 2023-12-19 02:27
Duplicate of #79

**Closed** 2023-12-19 02:41 UTC
Labels: enhancement
